# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# Shared API Gateway path resources for nested routes

resource "aws_api_gateway_resource" "path_device" {
  rest_api_id = module.api.rest_api_id
  parent_id   = module.api.rest_api_root_resource_id
  path_part   = "device"
}

resource "aws_api_gateway_resource" "path_feedly" {
  rest_api_id = module.api.rest_api_id
  parent_id   = module.api.rest_api_root_resource_id
  path_part   = "feedly"
}

resource "aws_api_gateway_resource" "path_user" {
  rest_api_id = module.api.rest_api_id
  parent_id   = module.api.rest_api_root_resource_id
  path_part   = "user"
}
