# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

terraform {
  backend "s3" {
    bucket               = "mantle-offlinemediadownloader-tfstate"
    key                  = "infra.tfstate"
    region               = "us-west-2"
    encrypt              = true
    dynamodb_table       = "TerraformStateLock"
    workspace_key_prefix = "env"
  }
}
