# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

module "database" {
  source = "../../mantle/modules/database/aurora-dsql"

  name_prefix         = module.core.name_prefix
  tags                = module.core.common_tags
  deletion_protection = var.environment == "prod"
}
