# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# DynamoDB table: idempotency
module "dynamodb_idempotency" {
  source      = "../../mantle/modules/dynamodb"
  table_name  = "idempotency"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags
  hash_key    = "id"
  attributes  = [{name = "id", type = "S"}]
  table_name_override = "${module.core.name_prefix}-MediaDownloader-Idempotency"
  ttl_attribute = "expiration"
}
