# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

module "eventbridge" {
  source      = "../../mantle/modules/eventbridge"
  bus_name    = "MediaDownloader"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags
}
