# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# Auto-generated from @RequiresTable decorators
# Do not edit manually - run: mantle generate permissions
# Generated at: 2026-03-24T19:27:51.421Z

locals {
  lambda_dsql_roles = {
    "ApiGatewayAuthorizer" = {
      role_name      = "lambda_api_gateway_authorizer"
      requires_admin = false
    }
    "CleanupExpiredRecords" = {
      role_name      = "lambda_cleanup_expired_records"
      requires_admin = false
    }
    "DeviceEvent" = {
      role_name      = "lambda_device_event"
      requires_admin = false
    }
    "DeviceRegister" = {
      role_name      = "lambda_device_register"
      requires_admin = false
    }
    "FeedlyWebhook" = {
      role_name      = "lambda_feedly_webhook"
      requires_admin = false
    }
    "FileHelpers" = {
      role_name      = "lambda_file_helpers"
      requires_admin = false
    }
    "FilesGet" = {
      role_name      = "lambda_files_get"
      requires_admin = false
    }
    "MigrateDSQL" = {
      role_name      = "lambda_migrate_d_s_q_l"
      requires_admin = false
    }
    "PruneDevices" = {
      role_name      = "lambda_prune_devices"
      requires_admin = false
    }
    "S3ObjectCreated" = {
      role_name      = "lambda_s3_object_created"
      requires_admin = false
    }
    "SendPushNotification" = {
      role_name      = "lambda_send_push_notification"
      requires_admin = false
    }
    "StartFileUpload" = {
      role_name      = "lambda_start_file_upload"
      requires_admin = false
    }
    "UserDelete" = {
      role_name      = "lambda_user_delete"
      requires_admin = false
    }
    "UserLogin" = {
      role_name      = "lambda_user_login"
      requires_admin = false
    }
    "UserLogout" = {
      role_name      = "lambda_user_logout"
      requires_admin = false
    }
    "UserRefresh" = {
      role_name      = "lambda_user_refresh"
      requires_admin = false
    }
    "UserRegister" = {
      role_name      = "lambda_user_register"
      requires_admin = false
    }
    "UserSubscribe" = {
      role_name      = "lambda_user_subscribe"
      requires_admin = false
    }
  }

  lambda_dsql_connect = {
    for k, v in local.lambda_dsql_roles : k => v if !v.requires_admin
  }

  lambda_dsql_admin = {
    for k, v in local.lambda_dsql_roles : k => v if v.requires_admin
  }
}
