# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- UserDelete ---

module "lambda_user_delete" {
  source = "../../mantle/modules/lambda"

  function_name      = "UserDelete"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/UserDelete"
  assume_role_policy = module.core.lambda_gateway_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  layers             = [local.adot_layer_arn]

  api_gateway_enabled = true

  environment_variables = merge(local.common_lambda_env, {
      DSQL_ROLE_NAME = local.lambda_dsql_roles["UserDelete"].role_name
      DSQL_ENDPOINT = module.database.cluster_endpoint
      DSQL_REGION = module.core.region
      GITHUB_PERSONAL_TOKEN = data.sops_file.secrets.data["github.issue.token"]
  })

    additional_policy_arns = [module.database.connect_policy_arn]

  inline_policies = {
    "SNSAccess" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = ["sns:DeleteEndpoint","sns:Subscribe","sns:Unsubscribe"]
        Resource = ["${aws_sns_topic.push_notifications.arn}","${aws_sns_platform_application.apns.arn}","${aws_sns_platform_application.apns.arn}/*"]
      }]
    })
  }
}

resource "aws_api_gateway_method" "user_delete" {
  rest_api_id   = module.api.rest_api_id
  resource_id   = aws_api_gateway_resource.path_user.id
  http_method   = "DELETE"
  authorization = "CUSTOM"
  authorizer_id = module.api.authorizer_id
}

resource "aws_api_gateway_integration" "user_delete" {
  rest_api_id             = module.api.rest_api_id
  resource_id             = aws_api_gateway_resource.path_user.id
  http_method             = aws_api_gateway_method.user_delete.http_method
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = module.lambda_user_delete.invoke_arn
}
