# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- UserLogin ---

module "lambda_user_login" {
  source = "../../mantle/modules/lambda"

  function_name      = "UserLogin"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/UserLogin"
  assume_role_policy = module.core.lambda_gateway_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  layers             = [local.adot_layer_arn]

  api_gateway_enabled = true

  environment_variables = merge(local.common_lambda_env, {
      API_BEARER_TOKEN = var.api_bearer_token
      DSQL_ROLE_NAME = local.lambda_dsql_roles["UserLogin"].role_name
      AUTH_SECRET = data.sops_file.secrets.data["platform.key"]
      APPLE_CLIENT_ID = data.sops_file.secrets.data["signInWithApple.config"]
      APPLE_CLIENT_SECRET = data.sops_file.secrets.data["signInWithApple.authKey"]
      AUTH_BASE_URL = "https://${module.api.rest_api_id}.execute-api.${module.core.region}.amazonaws.com/prod"
      APPLE_APP_BUNDLE_IDENTIFIER = var.apple_app_bundle_identifier
  })

    additional_policy_arns = [module.database.connect_policy_arn]
}

resource "aws_api_gateway_resource" "user_login" {
  rest_api_id = module.api.rest_api_id
  parent_id   = aws_api_gateway_resource.path_user.id
  path_part   = "login"
}

resource "aws_api_gateway_method" "user_login" {
  rest_api_id   = module.api.rest_api_id
  resource_id   = aws_api_gateway_resource.user_login.id
  http_method   = "POST"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "user_login" {
  rest_api_id             = module.api.rest_api_id
  resource_id             = aws_api_gateway_resource.user_login.id
  http_method             = aws_api_gateway_method.user_login.http_method
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = module.lambda_user_login.invoke_arn
}
