# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- SendPushNotification ---

module "lambda_send_push_notification" {
  source = "../../mantle/modules/lambda"

  function_name      = "SendPushNotification"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/SendPushNotification"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  layers             = [local.adot_layer_arn]

  api_gateway_enabled = false

  environment_variables = merge(local.common_lambda_env, {
      DSQL_ROLE_NAME = local.lambda_dsql_roles["SendPushNotification"].role_name
      DSQL_ENDPOINT = module.database.cluster_endpoint
      DSQL_REGION = module.core.region
  })

    additional_policy_arns = [module.database.connect_policy_arn]

  inline_policies = {
    "SNSAccess" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = ["sns:DeleteEndpoint","sns:Publish"]
        Resource = ["${aws_sns_topic.push_notifications.arn}","${aws_sns_platform_application.apns.arn}","${aws_sns_platform_application.apns.arn}/*"]
      }]
    })
  }

  sqs_trigger_arn     = module.queue_SendPushNotification.queue_arn
  sqs_trigger_enabled = true
}
