# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- FileHelpers ---

module "lambda_file_helpers" {
  source = "../../mantle/modules/lambda"

  function_name      = "FileHelpers"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/FileHelpers"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_level          = var.log_level
  tags               = module.core.common_tags

  api_gateway_enabled = false

    environment_variables = {
      API_BEARER_TOKEN = var.api_bearer_token
      DSQL_ENDPOINT = var.dsql_endpoint != "" ? var.dsql_endpoint : module.database.cluster_endpoint
      DSQL_ROLE_NAME = local.lambda_dsql_roles["FileHelpers"].role_name
      METRICS_NAMESPACE = "MediaDownloader"
    }

    additional_policy_arns = [module.database.connect_policy_arn]
}
