# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- PruneDevices ---

module "lambda_prune_devices" {
  source = "../../mantle/modules/lambda"

  function_name      = "PruneDevices"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/PruneDevices"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  timeout            = 300
  schedule_expression = "rate(1 day)"
  layers             = [local.adot_layer_arn]

  api_gateway_enabled = false

  environment_variables = merge(local.common_lambda_env, {
      API_BEARER_TOKEN = var.api_bearer_token
      DSQL_ROLE_NAME = local.lambda_dsql_roles["PruneDevices"].role_name
      APNS_SIGNING_KEY = data.sops_file.secrets.data["apns.staging.signingKey"]
      APNS_TEAM = data.sops_file.secrets.data["apns.staging.team"]
      APNS_KEY_ID = data.sops_file.secrets.data["apns.staging.keyId"]
      APNS_DEFAULT_TOPIC = data.sops_file.secrets.data["apns.staging.defaultTopic"]
      APNS_HOST = var.apns_host
  })

    additional_policy_arns = [module.database.connect_policy_arn]
}
