# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- CleanupExpiredRecords ---

module "lambda_cleanup_expired_records" {
  source = "../../mantle/modules/lambda"

  function_name       = "CleanupExpiredRecords"
  name_prefix         = module.core.name_prefix
  source_dir          = "${path.module}/../build/lambdas/CleanupExpiredRecords"
  assume_role_policy  = module.core.lambda_assume_role_policy
  xray_policy_arn     = module.core.lambda_xray_policy_arn
  region              = module.core.region
  account_id          = module.core.account_id
  environment         = var.environment
  log_retention_days  = var.log_retention_days
  log_level           = var.log_level
  tags                = module.core.common_tags
  timeout             = 60
  schedule_expression = "cron(0 3 * * ? *)"
  layers              = [local.adot_layer_arn]

  api_gateway_enabled = false

  environment_variables = merge(local.common_lambda_env, {
    API_BEARER_TOKEN = var.api_bearer_token
    DSQL_ROLE_NAME   = local.lambda_dsql_roles["CleanupExpiredRecords"].role_name
  })

  additional_policy_arns = [module.database.connect_policy_arn]
}
