# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- FeedlyWebhook ---

module "lambda_feedly_webhook" {
  source = "../../mantle/modules/lambda"

  function_name      = "FeedlyWebhook"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/FeedlyWebhook"
  assume_role_policy = module.core.lambda_gateway_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  layers             = [local.adot_layer_arn]

  api_gateway_enabled = true

  environment_variables = merge(local.common_lambda_env, {
      API_BEARER_TOKEN = var.api_bearer_token
      DSQL_ROLE_NAME = local.lambda_dsql_roles["FeedlyWebhook"].role_name
      SNS_QUEUE_URL = module.queue_SendPushNotification.queue_url
      PATH = var.path
      YTDLP_SLEEP_REQUESTS = var.ytdlp_sleep_requests
      YTDLP_SLEEP_INTERVAL = var.ytdlp_sleep_interval
      YTDLP_MAX_SLEEP_INTERVAL = var.ytdlp_max_sleep_interval
      YTDLP_BINARY_PATH = var.ytdlp_binary_path
      IDEMPOTENCY_TABLE_NAME = module.dynamodb_idempotency.table_name
  })

    additional_policy_arns = [module.database.connect_policy_arn]

  inline_policies = {
    "SQSSend_Sendpushnotification" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = "sqs:SendMessage"
        Resource = module.queue_SendPushNotification.queue_arn
      }]
    })
    "DynamoDBAccess_Idempotency" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = ["dynamodb:GetItem","dynamodb:PutItem","dynamodb:UpdateItem","dynamodb:DeleteItem","dynamodb:Query","dynamodb:Scan"]
        Resource = [
          "${module.dynamodb_idempotency.table_arn}",
          "${module.dynamodb_idempotency.table_arn}/*"
        ]
      }]
    })
    "EventBridgePutEvents" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = "events:PutEvents"
        Resource = module.eventbridge.bus_arn
      }]
    })
  }
}

resource "aws_api_gateway_resource" "feedly_webhook" {
  rest_api_id = module.api.rest_api_id
  parent_id   = aws_api_gateway_resource.path_feedly.id
  path_part   = "webhook"
}

resource "aws_api_gateway_method" "feedly_webhook" {
  rest_api_id   = module.api.rest_api_id
  resource_id   = aws_api_gateway_resource.feedly_webhook.id
  http_method   = "POST"
  authorization = "CUSTOM"
  authorizer_id = module.api.authorizer_id
}

resource "aws_api_gateway_integration" "feedly_webhook" {
  rest_api_id             = module.api.rest_api_id
  resource_id             = aws_api_gateway_resource.feedly_webhook.id
  http_method             = aws_api_gateway_method.feedly_webhook.http_method
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = module.lambda_feedly_webhook.invoke_arn
}
