# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

data "archive_file" "layer_yt_dlp" {
  type             = "zip"
  source_dir       = "${path.module}/../layers/yt-dlp"
  output_path      = "${path.module}/../build/layers/yt-dlp.zip"
  output_file_mode = "0644"
  excludes         = ["**/.DS_Store", "**/__pycache__/**", "**/*.pyc"]
}

resource "aws_lambda_layer_version" "yt_dlp" {
  layer_name               = "${module.core.name_prefix}-yt-dlp"
  filename                 = data.archive_file.layer_yt_dlp.output_path
  source_code_hash         = data.archive_file.layer_yt_dlp.output_base64sha256
  compatible_architectures = ["x86_64"]
  description              = "yt-dlp binary and YouTube cookies"
  skip_destroy             = true

  lifecycle {
    create_before_destroy = true
  }
}

data "archive_file" "layer_bgutil" {
  type             = "zip"
  source_dir       = "${path.module}/../layers/bgutil"
  output_path      = "${path.module}/../build/layers/bgutil.zip"
  output_file_mode = "0644"
  excludes         = ["**/.DS_Store", "**/__pycache__/**", "**/*.pyc"]
}

resource "aws_lambda_layer_version" "bgutil" {
  layer_name               = "${module.core.name_prefix}-bgutil"
  filename                 = data.archive_file.layer_bgutil.output_path
  source_code_hash         = data.archive_file.layer_bgutil.output_base64sha256
  compatible_architectures = ["x86_64"]
  description              = "bgutil PO-token provider for yt-dlp"
  skip_destroy             = true

  lifecycle {
    create_before_destroy = true
  }
}
