# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    sops = {
      source  = "carlpett/sops"
      version = ">= 1.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"
}

module "core" {
  source       = "../../mantle/modules/core"
  project_name = var.project_name
  environment  = var.environment
}

module "api" {
  source      = "../../mantle/modules/api-gateway"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags

  redeployment_trigger = sha1(join(",", [
      module.lambda_device_event.invoke_arn,
      module.lambda_device_register.invoke_arn,
      module.lambda_feedly_webhook.invoke_arn,
      module.lambda_files_get.invoke_arn,
      module.lambda_user_delete.invoke_arn,
      module.lambda_user_login.invoke_arn,
      module.lambda_user_logout.invoke_arn,
      module.lambda_user_refresh.invoke_arn,
      module.lambda_user_register.invoke_arn,
      module.lambda_user_subscribe.invoke_arn,
      "auth:none",
      "auth:authorizer",
      "auth:authorizer",
      "auth:authorizer",
      "auth:authorizer",
      "auth:none",
      "auth:authorizer",
      "auth:authorizer",
      "auth:none",
      "auth:authorizer",
    ]))

  authorizer_lambda_invoke_arn = module.lambda_api_gateway_authorizer.invoke_arn
  authorizer_enabled           = true
  authorizer_ttl_seconds       = 300
}