# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- MigrateDSQL ---
# Runs schema migrations and applies per-Lambda permissions on every deploy.

module "lambda_migrate_dsql" {
  source = "../../mantle/modules/lambda"

  function_name      = "MigrateDSQL"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/MigrateDSQL"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  tags               = module.core.common_tags
  timeout            = 300

  environment_variables = {
    DSQL_ENDPOINT         = module.database.cluster_endpoint
    DSQL_REGION           = module.core.region
    DSQL_ROLE_NAME        = "admin"
    METRICS_NAMESPACE = "MediaDownloader"
    AWS_ACCOUNT_ID    = module.core.account_id
    RESOURCE_PREFIX   = module.core.name_prefix
  }

  additional_policy_arns = [module.database.admin_connect_policy_arn]
}

resource "time_sleep" "wait_for_dsql" {
  depends_on      = [module.database, module.lambda_migrate_dsql]
  create_duration = "60s"
}

# Initial deploy: data source runs migrations on first cluster creation
data "aws_lambda_invocation" "run_migration" {
  function_name = module.lambda_migrate_dsql.function_name
  input         = jsonencode({ source = "terraform-deploy" })
  depends_on    = [time_sleep.wait_for_dsql]
}

# Subsequent deploys: re-invoke when Lambda code or permissions change.
# Data sources are evaluated during planning (before apply), so code/permission
# changes aren't picked up by the data source above. This resource triggers
# during apply when its hash inputs change.
resource "terraform_data" "rerun_migration" {
  triggers_replace = sha256(join(",", [
    filesha256("${path.module}/../build/lambdas/MigrateDSQL/index.mjs"),
    filesha256("${path.module}/../permissions/permissions.sql")
  ]))

  provisioner "local-exec" {
    command = <<-EOT
      aws lambda invoke --function-name ${module.lambda_migrate_dsql.function_name} --payload '{"source":"terraform-deploy-rerun"}' --cli-binary-format raw-in-base64-out /tmp/mantle-migrate-rerun.json >&2
      cat /tmp/mantle-migrate-rerun.json >&2
    EOT
  }

  depends_on = [module.lambda_migrate_dsql]
}

output "migration_result" {
  value = jsondecode(data.aws_lambda_invocation.run_migration.result)
}
