# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# SQS queue: send-push-notification
module "queue_send_push_notification" {
  source      = "../../mantle/modules/queue"
  queue_name  = "send-push-notification"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags
}
