# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# SQS queue: DownloadQueue
module "queue_DownloadQueue" {
  source                     = "../../mantle/modules/queue"
  queue_name                 = "DownloadQueue"
  name_prefix                = module.core.name_prefix
  tags                       = module.core.common_tags
  visibility_timeout_seconds = 900
}
