# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# SQS queue: SendPushNotification
module "queue_SendPushNotification" {
  source      = "../../mantle/modules/queue"
  queue_name  = "SendPushNotification"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags
}
