# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# SNS Resources

resource "aws_sns_topic" "push_notifications" {
  name = "${module.core.name_prefix}-PushNotifications"
  tags = module.core.common_tags
}

resource "aws_sns_topic" "operations_alerts" {
  name = "${module.core.name_prefix}-OperationsAlerts"
  tags = module.core.common_tags
}

resource "aws_iam_role" "sns_logging" {
  name = "${module.core.name_prefix}-SNSLogging"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "sns.amazonaws.com"
      }
    }]
  })

  tags = module.core.common_tags
}

resource "aws_iam_role_policy" "sns_logging" {
  name = "SNSCloudWatchLogging"
  role = aws_iam_role.sns_logging.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:PutMetricFilter",
        "logs:PutRetentionPolicy"
      ]
      Resource = "*"
    }]
  })
}

resource "aws_sns_platform_application" "apns" {
  name                = "${module.core.name_prefix}-MediaDownloader"
  platform            = var.environment == "production" ? "APNS" : "APNS_SANDBOX"
  platform_credential = data.sops_file.secrets.data["apns.staging.privateKey"]
  platform_principal  = data.sops_file.secrets.data["apns.staging.certificate"]

  depends_on = [aws_iam_role.sns_logging, aws_iam_role_policy.sns_logging]
}
