# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# S3 bucket + CloudFront distribution for files
module "storage_files" {
  source       = "../../mantle/modules/storage"
  bucket_name  = "files"
  name_prefix  = module.core.name_prefix
  project_name = var.project_name
  tags         = module.core.common_tags
  bucket_name_override = "${module.core.name_prefix}-mantle-offlinemediadownloader-videos"

  cloudfront_enabled    = true
  intelligent_tiering_enabled = true
  lambda_notifications = [
    {
      id                  = "S3ObjectCreated"
      lambda_function_arn = module.lambda_s3object_created.function_arn
      events              = ["s3:ObjectCreated:*"]
    }
  ]
}

resource "aws_s3_object" "asset_videos_default_file" {
  bucket       = module.storage_files.bucket_id
  key          = "videos/default-file.mp4"
  source       = "${path.module}/../static/videos/default-file.mp4"
  content_type = "video/mp4"
  etag         = filemd5("${path.module}/../static/videos/default-file.mp4")
}
