# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "media-downloader"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be one of: dev, staging, prod."
  }
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-west-2"
}

variable "api_bearer_token" {
  description = "Bearer token for API authentication"
  type        = string
  sensitive   = true
  default     = ""
}

variable "log_level" {
  description = "Application log level (DEBUG, INFO, WARN, ERROR)"
  type        = string
  default     = "INFO"
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days"
  type        = number
  default     = 14
}

variable "dsql_endpoint" {
  description = "Aurora DSQL cluster endpoint (set after initial provisioning or pass from database module)"
  type        = string
  default     = ""
}

variable "node_env" {
  description = "node env"
  type        = string
  default     = ""
}

variable "reserved_client_ip" {
  description = "reserved client ip"
  type        = string
  default     = ""
}

variable "multi_authentication_path_parts" {
  description = "multi authentication path parts"
  type        = string
  default     = ""
}

variable "dsql_region" {
  description = "dsql region"
  type        = string
  default     = ""
}

variable "apns_team" {
  description = "apns team"
  type        = string
  default     = ""
}

variable "apns_key_id" {
  description = "apns key id"
  type        = string
  default     = ""
  sensitive   = true
}

variable "apns_signing_key" {
  description = "apns signing key"
  type        = string
  default     = ""
  sensitive   = true
}

variable "apns_default_topic" {
  description = "apns default topic"
  type        = string
  default     = ""
}

variable "apns_host" {
  description = "apns host"
  type        = string
  default     = ""
}

variable "ytdlp_binary_path" {
  description = "ytdlp binary path"
  type        = string
  default     = ""
}

variable "github_personal_token" {
  description = "github personal token"
  type        = string
  default     = ""
  sensitive   = true
}

variable "auth_secret" {
  description = "auth secret"
  type        = string
  default     = ""
  sensitive   = true
}

variable "apple_client_id" {
  description = "apple client id"
  type        = string
  default     = ""
}

variable "apple_client_secret" {
  description = "apple client secret"
  type        = string
  default     = ""
  sensitive   = true
}

variable "apple_app_bundle_identifier" {
  description = "apple app bundle identifier"
  type        = string
  default     = ""
}
