# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "media-downloader"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be one of: dev, staging, prod."
  }
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-west-2"
}

variable "api_bearer_token" {
  description = "Bearer token for API authentication"
  type        = string
  sensitive   = true
  default     = ""
}

variable "log_level" {
  description = "Application log level (DEBUG, INFO, WARN, ERROR)"
  type        = string
  default     = "INFO"
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days"
  type        = number
  default     = 14
}

variable "dsql_endpoint" {
  description = "Aurora DSQL cluster endpoint (set after initial provisioning or pass from database module)"
  type        = string
  default     = ""
}

variable "node_env" {
  description = "node env"
  type        = string
  default     = ""
}

variable "reserved_client_ip" {
  description = "reserved client ip"
  type        = string
  default     = ""
}

variable "multi_authentication_path_parts" {
  description = "multi authentication path parts"
  type        = string
  default     = ""
}

variable "apns_team" {
  description = "apns team"
  type        = string
  default     = ""
}

variable "apns_key_id" {
  description = "apns key id"
  type        = string
  default     = ""
  sensitive   = true
}

variable "apns_signing_key" {
  description = "apns signing key"
  type        = string
  default     = ""
  sensitive   = true
}

variable "apns_default_topic" {
  description = "apns default topic"
  type        = string
  default     = ""
}

variable "apns_host" {
  description = "apns host"
  type        = string
  default     = ""
}

variable "ytdlp_sleep_requests" {
  description = "ytdlp sleep requests"
  type        = string
  default     = ""
}

variable "ytdlp_sleep_interval" {
  description = "ytdlp sleep interval"
  type        = string
  default     = ""
}

variable "ytdlp_max_sleep_interval" {
  description = "ytdlp max sleep interval"
  type        = string
  default     = ""
}

variable "ytdlp_binary_path" {
  description = "ytdlp binary path"
  type        = string
  default     = ""
}

variable "github_personal_token" {
  description = "github personal token"
  type        = string
  default     = ""
  sensitive   = true
}

variable "auth_secret" {
  description = "auth secret"
  type        = string
  default     = ""
  sensitive   = true
}

variable "apple_client_id" {
  description = "apple client id"
  type        = string
  default     = ""
}

variable "apple_client_secret" {
  description = "apple client secret"
  type        = string
  default     = ""
  sensitive   = true
}

variable "apple_app_bundle_identifier" {
  description = "apple app bundle identifier"
  type        = string
  default     = ""
}

# Project-specific custom variables

variable "resource_prefix" {
  description = "DEPRECATED: Legacy prefix for S3 bucket names only. New resources use module.core.name_prefix. Do not replicate in new instances. See ADR 0001."
  type        = string

  validation {
    condition     = contains(["stag", "prod"], var.resource_prefix)
    error_message = "Resource prefix must be 'stag' or 'prod'."
  }
}

variable "api_throttle_burst_limit" {
  description = "API Gateway throttle burst limit"
  type        = number
  default     = 100
}

variable "api_throttle_rate_limit" {
  description = "API Gateway throttle rate limit"
  type        = number
  default     = 50
}

variable "api_quota_limit" {
  description = "API Gateway daily quota limit"
  type        = number
  default     = 10000
}

variable "dsql_deletion_protection" {
  description = "Enable deletion protection for DSQL cluster"
  type        = bool
  default     = true
}

variable "enable_cloudwatch_dashboard" {
  description = "Enable CloudWatch dashboard (costs $3/month per environment)"
  type        = bool
  default     = false
}

variable "enable_cloudwatch_alarms" {
  description = "Enable CloudWatch alarms (first 10 free, then $0.10/alarm)"
  type        = bool
  default     = false
}

variable "cors_allowed_origins" {
  description = "Origins allowed to fetch media files via CORS (empty list disables CORS)"
  type        = list(string)
  default     = []

  validation {
    condition     = alltrue([for o in var.cors_allowed_origins : can(regex("^https?://", o))])
    error_message = "Each origin must start with http:// or https://."
  }
}

variable "image_uri_start_file_upload" {
  description = "ECR image URI for StartFileUpload container Lambda"
  type        = string
  default     = ""
}

variable "reserved_concurrency_start_file_upload" {
  description = "Reserved concurrent executions for StartFileUpload Lambda (-1 for unreserved)"
  type        = number
  default     = 1
}
