# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

variable "project_name" {
  description = "Project name"
  type        = string
  default     = "media-downloader"
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "Environment must be one of: dev, staging, prod."
  }
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-west-2"
}

variable "api_bearer_token" {
  description = "Bearer token for API authentication"
  type        = string
  sensitive   = true
  default     = ""
}

variable "log_level" {
  description = "Application log level (DEBUG, INFO, WARN, ERROR)"
  type        = string
  default     = "INFO"
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days"
  type        = number
  default     = 14
}

variable "dsql_endpoint" {
  description = "Aurora DSQL cluster endpoint (set after initial provisioning or pass from database module)"
  type        = string
  default     = ""
}

variable "node_env" {
  description = "node env"
  type        = string
  default     = ""
}
