Resources:
  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: AUTHORIZER
      Name: Lifegames iOS App
      Description: The API that supports the iOS App.
  MyUsagePlan:
    DependsOn:
      - MyApi
      - StageProduction
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref MyApi
          Stage: !Ref StageProduction
      Description: Internal consumption
      UsagePlanName: Basic
  MyUsagePlanKey:
    DependsOn:
      - iOSApiKey
      - MyUsagePlan
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref iOSApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref MyUsagePlan
  MyDeployment1589233275:
    DependsOn:
      - IFTTTWebhookFeedlyMethodPost
      - MyApi
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MyApi
      Description: "My deployment"
  Account:
    DependsOn:
      - GatewayLogRole
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt GatewayLogRole.Arn
  GatewayLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [apigateway.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  StageProduction:
    DependsOn:
      - GatewayLogRole
      - MyDeployment1589233275
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      Description: Production environment
      RestApiId: !Ref MyApi
      DeploymentId: !Ref MyDeployment1589233275
      Variables:
        Stack: Prod
      MethodSettings:
        - DataTraceEnabled: true
          HttpMethod: "*"
          LoggingLevel: INFO
          ResourcePath: "/*"
          MetricsEnabled: true
  iOSApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: iOSAppKey
      Description: The key for the iOS App
      Enabled: true
  Default400GatewayResponse:
    DependsOn:
      - MyApi
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseTemplates:
        application/json: "{\"error\":{\"code\":\"custom-4XX-generic\",\"message\":$context.error.messageString},\"requestId\":\"$context.requestId\"}"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref MyApi
  Default500GatewayResponse:
    DependsOn:
      - MyApi
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseTemplates:
        application/json: "{\"error\":{\"code\":\"custom-5XX-generic\",\"message\":$context.error.messageString},\"requestId\":\"$context.requestId\"}"
      ResponseType: DEFAULT_5XX
      RestApiId: !Ref MyApi
