AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first serverless application.

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 300
    MemorySize: 512


# Values to pass to your template at runtime (when you create or update a stack).
Parameters:
  ContentBucket:
    Type: String
  ContentKey:
    Type: String
  CodeKey:
    Type: String

Outputs:
  ApiUrl:
    Description: URL of the Prod stage of the API endpoint
    Value: !Sub "https://lifegames-app.execute-api.${AWS::Region}.amazonaws.com/Prod"
  FeedlyWebhookArn:
    Description: The ARN of the feedly webhook
    Value: !GetAtt FeedlyWebhook.Arn
  LayerARN:
    Description: The ARN for that Layer
    Value: !Ref NodeModulesLayer
    Export:
      Name: !Sub "${AWS::StackName}-LayerARN"
