Resources:
  RegisterUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref ContentBucket
        Key: !Ref CodeKey
      Handler: dist/main.handleRegisterUser
      Description:  Registers a new user.
      Environment:
        Variables:
          DynamoDBTable: !Ref DynamoUserTable
      Layers:
        - !Ref NodeModulesLayer
      Policies:
        - Statement:
            - Effect: Allow
              Action: 'dynamodb:UpdateItem'
              Resource: !GetAtt DynamoUserTable.Arn
        - Statement:
            - Effect: Allow
              Action: 'secretsmanager:GetSecretValue'
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/SignInWithApple/*
                - !Ref SecretJWTKey
  RegisterUserResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt MyApi.RootResourceId
      PathPart: "registerUser"
  RegisterUserMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: true
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref MyAuthorizer
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterUser.Arn}/invocations
      OperationName: registerUser
      ResourceId: !Ref RegisterUserResource
      RestApiId: !Ref MyApi
  RegisterUserMethodFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApi}/*/*/*
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt RegisterUser.Arn
  DynamoUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: Users
