/**
 * Generated Zod schemas from TypeSpec definitions
 * DO NOT EDIT - This file is auto-generated by scripts/generateApiTypes.ts
 */
import {z} from 'zod'

// YouTube URL regex pattern for validation
const youtubeUrlPattern = /^((?:https?:)?\/\/)?((?:www|m)\.)?((?:youtube(?:-nocookie)?\.com|youtu.be))(\/(?:[\w-]+\?v=|embed\/|live\/|v\/)?)?([\w-]+)(\S+)?$/

export const fileStatusSchema = z.enum(['Queued', 'Downloading', 'Downloaded', 'Failed'])

export const errorResponseSchema = z.object({error: z.object({code: z.string(), message: z.string()}), requestId: z.string()})

export const unauthorizedErrorSchema = z.object({error: z.object({code: z.literal('Unauthorized'), message: z.string()}), requestId: z.string()})

export const forbiddenErrorSchema = z.object({error: z.object({code: z.literal('Forbidden'), message: z.string()}), requestId: z.string()})

export const internalServerErrorSchema = z.object({error: z.object({code: z.literal('InternalServerError'), message: z.string()}), requestId: z.string()})

export const fileSchema = z.object({
  fileId: z.string(),
  key: z.string().optional(),
  size: z.number().optional(),
  status: fileStatusSchema.optional(),
  title: z.string().optional(),
  publishDate: z.string().optional(),
  authorName: z.string().optional(),
  authorUser: z.string().optional(),
  contentType: z.string().optional(),
  description: z.string().optional(),
  url: z.string().url().optional()
})

export const fileListResponseSchema = z.object({contents: z.array(fileSchema), keyCount: z.number()})

export const deviceSchema = z.object({
  deviceId: z.string(),
  name: z.string(),
  systemName: z.string(),
  systemVersion: z.string(),
  token: z.string(),
  endpointArn: z.string().optional()
})

export const deviceRegistrationRequestSchema = z.object({
  deviceId: z.string(),
  name: z.string(),
  systemName: z.string(),
  systemVersion: z.string(),
  token: z.string()
})

export const deviceRegistrationResponseSchema = z.object({endpointArn: z.string()})

export const feedlyWebhookRequestSchema = z.object({
  articleFirstImageURL: z.string().url().optional(),
  articleCategories: z.string().optional(),
  articlePublishedAt: z.string().optional(),
  articleTitle: z.string().optional(),
  articleURL: z.string().regex(youtubeUrlPattern, 'is not a valid YouTube URL'),
  createdAt: z.string().optional(),
  sourceFeedURL: z.string().url().optional(),
  sourceTitle: z.string().optional(),
  sourceURL: z.string().url().optional(),
  backgroundMode: z.boolean().optional()
})

export const webhookResponseSchema = z.object({status: z.union([z.literal('Dispatched'), z.literal('Initiated'), z.literal('Accepted')])})

export const userLoginRequestSchema = z.object({idToken: z.string()})

export const userLoginResponseSchema = z.object({token: z.string(), expiresAt: z.string(), sessionId: z.string(), userId: z.string()})

export const userRegistrationRequestSchema = z.object({idToken: z.string(), firstName: z.string().optional(), lastName: z.string().optional()})

export const userRegistrationResponseSchema = z.object({token: z.string(), expiresAt: z.string(), sessionId: z.string(), userId: z.string()})

export const userSubscriptionRequestSchema = z.object({endpointArn: z.string(), topicArn: z.string()})

export const userSubscriptionResponseSchema = z.object({subscriptionArn: z.string()})

export const tokenRefreshResponseSchema = z.object({token: z.string(), expiresAt: z.string(), sessionId: z.string(), userId: z.string()})

export const clientEventRequestSchema = z.object({message: z.string()})
