/**
 * Generated TypeScript types from Zod schemas
 * DO NOT EDIT - This file is auto-generated by scripts/generateApiTypes.ts
 */
import {z} from 'zod'
import * as schemas from './schemas'

export type FileStatusApi = z.infer<typeof schemas.fileStatusSchema>
export type ErrorResponse = z.infer<typeof schemas.errorResponseSchema>
export type UnauthorizedError = z.infer<typeof schemas.unauthorizedErrorSchema>
export type ForbiddenError = z.infer<typeof schemas.forbiddenErrorSchema>
export type InternalServerError = z.infer<typeof schemas.internalServerErrorSchema>
export type FileApi = z.infer<typeof schemas.fileSchema>
export type FileListResponse = z.infer<typeof schemas.fileListResponseSchema>
export type DeviceApi = z.infer<typeof schemas.deviceSchema>
export type DeviceRegistrationRequest = z.infer<typeof schemas.deviceRegistrationRequestSchema>
export type DeviceRegistrationResponse = z.infer<typeof schemas.deviceRegistrationResponseSchema>
export type FeedlyWebhookRequest = z.infer<typeof schemas.feedlyWebhookRequestSchema>
export type WebhookResponse = z.infer<typeof schemas.webhookResponseSchema>
export type UserLoginRequest = z.infer<typeof schemas.userLoginRequestSchema>
export type UserLoginResponse = z.infer<typeof schemas.userLoginResponseSchema>
export type UserRegistrationRequest = z.infer<typeof schemas.userRegistrationRequestSchema>
export type UserRegistrationResponse = z.infer<typeof schemas.userRegistrationResponseSchema>
export type UserSubscriptionRequest = z.infer<typeof schemas.userSubscriptionRequestSchema>
export type UserSubscriptionResponse = z.infer<typeof schemas.userSubscriptionResponseSchema>
export type TokenRefreshResponse = z.infer<typeof schemas.tokenRefreshResponseSchema>
export type ClientEventRequest = z.infer<typeof schemas.clientEventRequestSchema>
