name: 'Setup Node.js and pnpm'
description: 'Standard Node.js and pnpm setup with caching'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Report cache status
      shell: bash
      run: |
        if [ "${{ steps.setup-node.outputs.cache-hit }}" = "true" ]; then
          echo "::notice::pnpm cache HIT - dependencies restored from cache"
        else
          echo "::notice::pnpm cache MISS - installing dependencies fresh"
        fi

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
