/**
 * Generated TypeScript enums from Terraform resource definitions.
 * DO NOT EDIT - This file is auto-generated by scripts/generateResourceEnums.ts
 *
 * Regenerate with: pnpm run generate:resource-enums
 * Source: build/terraform-resources.json
 * Generated at: 2026-03-26T21:21:52.237Z
 */

/** S3 bucket resources from Terraform */
export enum S3Resource {}

/** SQS queue resources from Terraform */
export enum SQSResource {}

/** SNS topic resources from Terraform */
export enum SNSTopicResource {
  operations_alerts = 'operations_alerts',
  push_notifications = 'push_notifications'
}

/** SNS platform application resources from Terraform */
export enum SNSPlatformResource {
  apns = 'apns'
}

/** EventBridge event bus resources from Terraform */
export enum EventBridgeResource {}

/** DynamoDB table resources from Terraform */
export enum DynamoDBResource {}

/** Union of all SNS resources (topics and platform applications) */
export type SNSResource = SNSTopicResource | SNSPlatformResource

/** Union of all service resources for @RequiresServices decorator */
export type TerraformResource = S3Resource | SQSResource | SNSTopicResource | SNSPlatformResource | EventBridgeResource | DynamoDBResource
