/**
 * Generated TypeScript enums from Terraform resource definitions.
 * DO NOT EDIT - This file is auto-generated by scripts/generateResourceEnums.ts
 *
 * Regenerate with: pnpm run generate:resource-enums
 * Source: build/terraform-resources.json
 * Generated at: 2026-01-19T16:28:45.991Z
 */

/** S3 bucket resources from Terraform */
export enum S3Resource {
  Files = 'Files'
}

/** SQS queue resources from Terraform */
export enum SQSResource {
  DownloadDLQ = 'DownloadDLQ',
  DownloadQueue = 'DownloadQueue',
  SendPushNotification = 'SendPushNotification',
  SendPushNotificationDLQ = 'SendPushNotificationDLQ'
}

/** SNS topic resources from Terraform */
export enum SNSTopicResource {
  OperationsAlerts = 'OperationsAlerts',
  PushNotifications = 'PushNotifications'
}

/** SNS platform application resources from Terraform */
export enum SNSPlatformResource {
  OfflineMediaDownloader = 'OfflineMediaDownloader'
}

/** EventBridge event bus resources from Terraform */
export enum EventBridgeResource {
  MediaDownloader = 'MediaDownloader'
}

/** DynamoDB table resources from Terraform */
export enum DynamoDBResource {
  IdempotencyTable = 'IdempotencyTable'
}

/** Union of all SNS resources (topics and platform applications) */
export type SNSResource = SNSTopicResource | SNSPlatformResource

/** Union of all service resources for @RequiresServices decorator */
export type TerraformResource = S3Resource | SQSResource | SNSTopicResource | SNSPlatformResource | EventBridgeResource | DynamoDBResource
