bail: true
extension:
  - ts
full-trace: true
ignore:
  - 'src/util/mocha-setup.ts'
package: ./package.json
require:
  - '@babel/register'
  - 'ts-node/register'
  - 'src/util/mocha-setup.ts'
spec: 'src/**/**/*.test.ts'
loader: 'ts-node/esm'
