/**
 * Terraform Resource Extraction Script
 *
 * Extracts AWS resource names from build/infrastructure.json
 * (generated by hcl2json in bin/build-dependencies.sh)
 *
 * Output: build/terraform-resources.json
 *
 * Usage: pnpm run extract:terraform-resources
 *
 * @see docs/wiki/Infrastructure/Lambda-Decorators.md
 */
import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'fs'
import {dirname, join} from 'path'
import {fileURLToPath} from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const projectRoot = join(__dirname, '..')

interface ResourceEntry {
  /** Terraform resource name (e.g., 'Files', 'DownloadQueue') */
  name: string
  /** Full Terraform resource ID (e.g., 'aws_s3_bucket.Files') */
  terraformId: string
  /** Terraform ARN reference expression (e.g., 'aws_s3_bucket.Files.arn') */
  arnRef: string
}

interface TerraformResourceManifest {
  s3Buckets: ResourceEntry[]
  sqsQueues: ResourceEntry[]
  snsTopics: ResourceEntry[]
  snsPlatformApplications: ResourceEntry[]
  eventBridgeBuses: ResourceEntry[]
  generatedAt: string
}

interface InfrastructureJson {
  resource?: {
    aws_s3_bucket?: Record<string, unknown[]>
    aws_sqs_queue?: Record<string, unknown[]>
    aws_sns_topic?: Record<string, unknown[]>
    aws_sns_platform_application?: Record<string, unknown[]>
    aws_cloudwatch_event_bus?: Record<string, unknown[]>
  }
}

/**
 * Extract resources of a specific type from infrastructure.json
 */
function extractResources(
  resources: Record<string, unknown[]> | undefined,
  terraformType: string
): ResourceEntry[] {
  if (!resources) {
    return []
  }

  return Object.keys(resources).map((name) => {
    // SNS platform applications use array indexing due to conditional creation
    const arnSuffix = terraformType === 'aws_sns_platform_application' ? '[0].arn' : '.arn'

    return {
      name,
      terraformId: `${terraformType}.${name}`,
      arnRef: `${terraformType}.${name}${arnSuffix}`
    }
  })
}

/**
 * Main extraction function
 */
async function extractTerraformResources(): Promise<TerraformResourceManifest> {
  const infrastructurePath = join(projectRoot, 'build/infrastructure.json')

  if (!existsSync(infrastructurePath)) {
    console.error('Error: build/infrastructure.json not found.')
    console.error('Run: pnpm run build:dependencies first.')
    process.exit(1)
  }

  console.log('Reading build/infrastructure.json...')
  const infrastructure: InfrastructureJson = JSON.parse(
    readFileSync(infrastructurePath, 'utf-8')
  )

  const resources = infrastructure.resource

  if (!resources) {
    console.error('Error: No "resource" key found in infrastructure.json')
    process.exit(1)
  }

  const manifest: TerraformResourceManifest = {
    s3Buckets: extractResources(resources.aws_s3_bucket, 'aws_s3_bucket'),
    sqsQueues: extractResources(resources.aws_sqs_queue, 'aws_sqs_queue'),
    snsTopics: extractResources(resources.aws_sns_topic, 'aws_sns_topic'),
    snsPlatformApplications: extractResources(
      resources.aws_sns_platform_application,
      'aws_sns_platform_application'
    ),
    eventBridgeBuses: extractResources(
      resources.aws_cloudwatch_event_bus,
      'aws_cloudwatch_event_bus'
    ),
    generatedAt: new Date().toISOString()
  }

  return manifest
}

/**
 * Main entry point
 */
async function main(): Promise<void> {
  try {
    const manifest = await extractTerraformResources()

    // Ensure build directory exists
    const buildDir = join(projectRoot, 'build')
    if (!existsSync(buildDir)) {
      mkdirSync(buildDir, {recursive: true})
    }

    // Write manifest
    const outputPath = join(buildDir, 'terraform-resources.json')
    writeFileSync(outputPath, JSON.stringify(manifest, null, 2))

    console.log(`\nGenerated ${outputPath}`)
    console.log('\nExtracted Terraform resources:')
    console.log(`  S3 Buckets:              ${manifest.s3Buckets.map((r) => r.name).join(', ') || '(none)'}`)
    console.log(`  SQS Queues:              ${manifest.sqsQueues.map((r) => r.name).join(', ') || '(none)'}`)
    console.log(`  SNS Topics:              ${manifest.snsTopics.map((r) => r.name).join(', ') || '(none)'}`)
    console.log(`  SNS Platform Apps:       ${manifest.snsPlatformApplications.map((r) => r.name).join(', ') || '(none)'}`)
    console.log(`  EventBridge Buses:       ${manifest.eventBridgeBuses.map((r) => r.name).join(', ') || '(none)'}`)
  } catch (error) {
    console.error('Failed to extract Terraform resources:', error)
    process.exit(1)
  }
}

main()
