/**
 * Resource Enum Generation Script
 *
 * Generates TypeScript enum definitions from build/terraform-resources.json.
 * These enums provide type-safe resource references for @RequiresServices decorators.
 *
 * Output: src/types/generatedResources.ts
 *
 * Usage: pnpm run generate:resource-enums
 *
 * @see docs/wiki/Infrastructure/Lambda-Decorators.md
 */
import {existsSync, readFileSync, writeFileSync} from 'fs'
import {dirname, join} from 'path'
import {fileURLToPath} from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const projectRoot = join(__dirname, '..')

interface ResourceEntry {
  name: string
  terraformId: string
  arnRef: string
}

interface TerraformResourceManifest {
  s3Buckets: ResourceEntry[]
  sqsQueues: ResourceEntry[]
  snsTopics: ResourceEntry[]
  snsPlatformApplications: ResourceEntry[]
  eventBridgeBuses: ResourceEntry[]
  generatedAt: string
}

/**
 * Generate enum definition string
 */
function generateEnum(enumName: string, resources: ResourceEntry[], docComment: string): string {
  if (resources.length === 0) {
    return `/** ${docComment} */\nexport enum ${enumName} {}\n`
  }

  const entries = resources.map((r) => `  ${r.name} = '${r.name}'`).join(',\n')

  return `/** ${docComment} */
export enum ${enumName} {
${entries}
}
`
}

/**
 * Generate the full TypeScript file content
 */
function generateTypeScriptFile(manifest: TerraformResourceManifest): string {
  const header = `/**
 * Generated TypeScript enums from Terraform resource definitions.
 * DO NOT EDIT - This file is auto-generated by scripts/generateResourceEnums.ts
 *
 * Regenerate with: pnpm run generate:resource-enums
 * Source: build/terraform-resources.json
 * Generated at: ${manifest.generatedAt}
 */

`

  const s3Enum = generateEnum('S3Resource', manifest.s3Buckets, 'S3 bucket resources from Terraform')
  const sqsEnum = generateEnum('SQSResource', manifest.sqsQueues, 'SQS queue resources from Terraform')
  const snsTopicEnum = generateEnum('SNSTopicResource', manifest.snsTopics, 'SNS topic resources from Terraform')
  const snsPlatformEnum = generateEnum(
    'SNSPlatformResource',
    manifest.snsPlatformApplications,
    'SNS platform application resources from Terraform'
  )
  const eventBridgeEnum = generateEnum(
    'EventBridgeResource',
    manifest.eventBridgeBuses,
    'EventBridge event bus resources from Terraform'
  )

  const typeDefinitions = `
/** Union of all SNS resources (topics and platform applications) */
export type SNSResource = SNSTopicResource | SNSPlatformResource

/** Union of all service resources for @RequiresServices decorator */
export type TerraformResource = S3Resource | SQSResource | SNSTopicResource | SNSPlatformResource | EventBridgeResource
`

  return header + s3Enum + '\n' + sqsEnum + '\n' + snsTopicEnum + '\n' + snsPlatformEnum + '\n' + eventBridgeEnum + typeDefinitions
}

/**
 * Main entry point
 */
async function main(): Promise<void> {
  const manifestPath = join(projectRoot, 'build/terraform-resources.json')

  if (!existsSync(manifestPath)) {
    console.error('Error: build/terraform-resources.json not found.')
    console.error('Run: pnpm run extract:terraform-resources first.')
    process.exit(1)
  }

  console.log('Reading build/terraform-resources.json...')
  const manifest: TerraformResourceManifest = JSON.parse(readFileSync(manifestPath, 'utf-8'))

  console.log(`Loaded resources from: ${manifest.generatedAt}`)

  // Generate TypeScript file
  const content = generateTypeScriptFile(manifest)

  // Write to src/types/generatedResources.ts
  const outputPath = join(projectRoot, 'src/types/generatedResources.ts')
  writeFileSync(outputPath, content)

  console.log(`\nGenerated ${outputPath}`)
  console.log('\nGenerated enums:')
  console.log(`  S3Resource:           ${manifest.s3Buckets.length} value(s)`)
  console.log(`  SQSResource:          ${manifest.sqsQueues.length} value(s)`)
  console.log(`  SNSTopicResource:     ${manifest.snsTopics.length} value(s)`)
  console.log(`  SNSPlatformResource:  ${manifest.snsPlatformApplications.length} value(s)`)
  console.log(`  EventBridgeResource:  ${manifest.eventBridgeBuses.length} value(s)`)
}

main().catch((error) => {
  console.error('Failed to generate resource enums:', error)
  process.exit(1)
})
