/**
 * Documentation Structure Rule
 * HIGH: Enforces documentation directory conventions
 *
 * This rule validates that files in docs/ follow the established convention:
 * - docs/wiki/ = All human-readable markdown documentation
 * - docs/api/ = API specifications (OpenAPI, SwaggerUI)
 * - docs/ root = Machine-readable files only (JSON, txt, auto-generated md)
 *
 * @see docs/wiki/Meta/Documentation-Structure.md
 */

import fs from 'fs'
import path from 'path'
import type {SourceFile} from 'ts-morph'
import {createViolation} from '../types'
import type {ValidationRule, Violation} from '../types'

const RULE_NAME = 'docs-structure'
const SEVERITY = 'HIGH' as const

/**
 * Allowed files in docs/ root (not in subdirectories)
 * These are machine-readable or auto-generated files
 */
const ALLOWED_DOCS_ROOT_FILES = [
  'doc-code-mapping.json',
  'doc-code-mapping.schema.json',
  'llms.txt',
  'llms-full.txt', // gitignored but allowed
  'terraform.md' // auto-generated by terraform-docs
]

/**
 * Allowed subdirectories in docs/
 */
const ALLOWED_DOCS_SUBDIRS = ['wiki', 'api', 'source']

export const docsStructureRule: ValidationRule = {
  name: RULE_NAME,
  description:
    'Enforces documentation directory conventions: markdown in docs/wiki/, machine files in docs/ root, API specs in docs/api/',
  severity: SEVERITY,
  appliesTo: ['docs/**/*'],
  excludes: ['docs/wiki/**', 'docs/api/**', 'docs/source/**'],

  validate(_sourceFile: SourceFile, filePath: string): Violation[] {
    // This rule validates based on file path only, not content
    void _sourceFile
    const violations: Violation[] = []

    // Skip if not in docs/ directory
    if (!filePath.startsWith('docs/')) {
      return violations
    }

    // Parse the path
    const pathParts = filePath.split('/')

    // If file is directly in docs/ root
    if (pathParts.length === 2) {
      const fileName = pathParts[1]

      // Check if it's an allowed root file
      if (!ALLOWED_DOCS_ROOT_FILES.includes(fileName)) {
        // Check if it's a markdown file (should be in wiki/)
        if (fileName.endsWith('.md')) {
          violations.push(
            createViolation(RULE_NAME, SEVERITY, 1, `Markdown file "${fileName}" should be in docs/wiki/, not docs/ root`, {
              suggestion: `Move to docs/wiki/[Category]/${fileName} where Category is one of: AWS, Conventions, Infrastructure, Integration, MCP, Meta, Testing, TypeScript`
            })
          )
        } else {
          violations.push(
            createViolation(RULE_NAME, 'MEDIUM', 1, `Unexpected file "${fileName}" in docs/ root`, {
              suggestion: `Only these files allowed in docs/ root: ${ALLOWED_DOCS_ROOT_FILES.join(', ')}`
            })
          )
        }
      }
    }

    // If file is in a subdirectory of docs/
    if (pathParts.length >= 3) {
      const subdir = pathParts[1]

      // Check if it's in an allowed subdirectory
      if (!ALLOWED_DOCS_SUBDIRS.includes(subdir)) {
        violations.push(
          createViolation(RULE_NAME, SEVERITY, 1, `Unexpected subdirectory "docs/${subdir}/" - not an allowed docs subdirectory`, {
            suggestion: `Allowed subdirectories: ${ALLOWED_DOCS_SUBDIRS.map((d) => `docs/${d}/`).join(', ')}. Move markdown files to docs/wiki/.`
          })
        )
      }
    }

    return violations
  }
}

/**
 * Validate docs structure from filesystem (for shell scripts and CI)
 * Returns list of violations as strings
 */
export function validateDocsStructure(projectRoot: string): string[] {
  const violations: string[] = []

  const docsDir = path.join(projectRoot, 'docs')
  if (!fs.existsSync(docsDir)) {
    return ['docs/ directory not found']
  }

  // Read docs/ directory
  const entries = fs.readdirSync(docsDir, {withFileTypes: true})

  for (const entry of entries) {
    if (entry.isFile()) {
      // Check if file is allowed in root
      if (!ALLOWED_DOCS_ROOT_FILES.includes(entry.name)) {
        if (entry.name.endsWith('.md')) {
          violations.push(`Markdown file "${entry.name}" should be in docs/wiki/, not docs/ root`)
        } else {
          violations.push(`Unexpected file "${entry.name}" in docs/ root`)
        }
      }
    } else if (entry.isDirectory()) {
      // Check if directory is allowed
      if (!ALLOWED_DOCS_SUBDIRS.includes(entry.name)) {
        violations.push(`Unexpected subdirectory "docs/${entry.name}/" - should use docs/wiki/ for documentation`)
      }
    }
  }

  return violations
}
