name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/gallium]
    steps:
    - uses: actions/checkout@v3

    - name: Build artifacts
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install hcl2json
      id: brew-install-hcl2json
      run: brew install hcl2json

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Setup directories
      id: setup
      run: mkdir build

    - name: Build dependencies
      id: build-dependencies
      run: npm run build-dependencies

    - name: Webpack Build
      id: build
      run: npm run build

    - name: Run Tests
      run: npm run test
      env:
        CI: true
