name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
        terraform_version: 0.15.1

    - name: Build artifacts
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Webpack Build
      id: build
      run: npm run build

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      id: plan
      run: terraform plan -refresh=false -no-color -out ./../build/plan
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2

    - name: Terraform Show
      run: terraform show -json ./../build/plan > ./../build/terraform.json
      working-directory: ./terraform

    - name: Build Terraform Types
      run: npm run build-terraform-types

    - name: Run Tests
      run: npm run test-production
      env:
        CI: true
